### ISSUE TITLE
Support LaTeX Expressions?

### ISSUE THREAD

**Issue by Exr0n** [shankar2k/math-at-point#1]
Hi! This looks really cool and seems to work great in org-mode which I use for quick notes! I wonder if it could be extended to support LaTeX expressions? 

I'm not too familiar with Elisp or this codebase, but I wonder if it's possible to check whether the point is in a LaTeX fragment using, eg. [`org-element-at-point`](https://github.com/tecosaur/LaTeX-auto-activating-snippets/blob/master/laas.el#L74)?
Perhaps calc's LaTeX language mode could also be leveraged?

Do you think this feature makes sense? Mostly, I'm hoping to be able to evaluate fractions and complex exponents.

**Comment by shankar2k** [comment]
That's a good idea. I'll look into it. I'm concerned that LaTeX equations are too rich to be unambiguously matched at point, but maybe I can leverage the fact that they are delimited by '$'s

**Comment by Exr0n** [comment]
Not sure if you use org-mode, but that's what I mostly use. I think there is a way of getting the element contents from `org-element-at-point` the way laas-mode (linked above) does? 

And by the way, I personally use `$..$` for inline and `\[ ... \]` for display math, but I believe the dollar signs are discouraged/being deprecated. The new inline syntax is `\( ... \)`

**Comment by shankar2k** [comment]
I do use org-mode, but haven't use LaTeX in years. It looks like there is a nice function `org-inside-LaTeX-fragment-p` that returns the delimiter and the location of the first one. Can you provide me with an example LaTeX fragment and the result you would like `math-at-point` to display?

**Comment by Exr0n** [comment]
Here's a test document. 
```org
#+AUTHOR: Exr0n
#+DATE: 06 May 2021
* Heading
  Lets do some cool arithmetic! Let $x = 3$. Then,

  \[\begin{aligned}
  x ^{\frac{2}{3}} = 3<cursor> ^{\frac{2}{3}} =
  \end{aligned}\]
```

**Comment by quantumish** [comment]
Maybe some working with calc's [embedded-mode](https://www.gnu.org/software/emacs/manual/html_node/calc/Basic-Embedded-Mode.html) would help, as it can recognize LaTeX equation delimiters — although to my understanding it's a pretty different system than `calc-eval`. 

Another possible idea is looking into somehow setting `calc-language` to `'latex` so that `calc-eval` can evaluate properly (this wouldn't search for delimiters though so maybe a combo with `org-element-at-point` would be best) yet I haven't figured out a way to do this. `calc-eval`'s source code definitely checks for `calc-language` but running something like `(setq calc-language 'latex)` before a `calc-eval` doesn't do anything and my elisp knowledge is very limited.

**Comment by shankar2k** [comment]
If we run`(org-inside-LaTeX-fragment-p)` at the point, we obtain `"(#("\\begin{aligned}" 0 15 (fontified t)) . 316)"`. This means that we can (at least sometimes) detect that we are in a LaTeX fragment.

If we evaluate the following:
```
(let ((calc-language 'latex))
  (calc-eval "  3 ^{\\frac{2}{3}}"))
```
We obtain the right answer `"2.08008382306"`. The question is, how do we detect the boundary of the latex expression? Are they always delimited by "="s or are at the beginning or end of line?

**Comment by Exr0n** [comment]
Perhaps equal-sign-delamination is good enough for daily use. I wonder if there is a way to check for all relational operators, such as `<`, `>`, `\le`, `\ge`, `\equiv` (off the top of my head)?

Does LaTeX even understand math expressions vs. eg. logical expressions? If so, there may already exist a solution..

**Comment by shankar2k** [comment]
@Exr0n I created a develop branch to implement support for LaTeX math expressions. Can you give it a try and let me know if it works for you? 

Please note that because this detects and parses LaTeX fragments using ``org-inside-LaTeX-fragment-p``, it recognizes LaTeX fragments delimited by ``\begin{}``/``\end{}``, ``\[``/``\]``, ``\(``/``\)``, and ``$$``, but expressions delimited by single `$`s are not supported.

**Comment by Exr0n** [comment]
@shankar2k I switched to the develop branch (`00708d35`), and I see `math-at-point`, `math-at-point-simple`, and `math-at-point-latex`. However, they all seem to echo "Defining as dynamic an already lexical var"... I'm probably doing something silly.

```
$$
2 + 3 <cursor>
$$
```

**Comment by shankar2k** [comment]
@Exr0n thanks for the test case. It highlighted a few more bugs that I believe I have fixed. Can you give it another try? Also, what version of Emacs are you using?

**Comment by Exr0n** [comment]
@shankar2k Sorry I didn't see these notifs... testing on that doc works!

However, a few things still seem broken... maybe because LaTeX has letters in control sequences?

```
$$
4<cursor>^{\frac{1}{2}}
$$
```
gets `4 => 4`


```
$$
4^<cursor>{\frac{1}{2}}
$$
```
gets the quick calc pop-up (doesn't seem to be detecting that it's in a math expression)

```
$$
4^{\fr<cursor>ac{1}<cursor>{2}<cursor>}
$$
```
Each of these cursor positions also get the quick calc pop-up

```
$$
4^{\frac{<cursor>1<cursor>}{<cursor>2<cursor>}}
$$
```
And these ones output `1 => 1` and `2 => 2` respectively.

Thank you so much for your support! This all just looks like magical elisp-ninja-ing :)

**Comment by Exr0n** [comment]
Oh, and I'm using
```
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4)
 of 2021-05-01
```

**Comment by shankar2k** [comment]
@Exr0n I haven't been able to reproduce the output you are seeing. The behavior you are observing would occur if you were searching for a non-LaTeX math expression at point, which could happen if at the point `(org-inside-LaTeX-fragment-p)` returns `nil`. To make it clear which type of expression is being search for, I split off the behavior for normal non-LaTeX math expressions into its own function `math-at-point-expression`.

Please update to the latest version of the develop branch (bea1ab6). Then, at each of the cursor points in your example, could you run the the commands `M-x math-at-point`, `M-x math-at-point-latex`, and `M-x math-at-point-expression`, and tell me the outputs for each?

**Comment by shankar2k** [comment]
> 
> 
> Oh, and I'm using
> 
> ```
> GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4)
>  of 2021-05-01
> ```

To be clear, I tested on my own system, Emacs 27.2 on Windows 10, as well as a Linux VM with Emacs 28.0.50, and all of the examples I tried worked properly. To make sure there is no interference from your existing configuration. you might want to try `emacs -Q` and then load the minimal setup needed to run `math-at-point`:

```
(add-to-list 'load-path "<path to>/math-at-point")
(require 'math-at-point)
(global-unset-key (kbd "C-z"))
(global-set-key (kbd "C-z =") 'math-at-point)
```

**Comment by Exr0n** [comment]
Hmm, I guess I failed to pull the develop branch. It works now, sorry for the confusion!

This is looking really great! Thank you so much for your active development and elisp magic, this is a beautiful example of the power of open-source.

**Comment by shankar2k** [comment]
I'm glad that my package is useful to you. Thank you for your help with testing this!
