### ISSUE TITLE
Doesn't handle summing negative numbers

### ISSUE THREAD

**Issue by daemianmack** [shankar2k/math-at-point#2]
Hey there, thanks for this tool!

I've noticed the following form doesn't seem to get recognized correctly by `math-at-point`...

```
3 + -20

;;=>

Result -20 => -20
```

**Comment by shankar2k** [comment]
Hello,

Thanks for bringing this to my attention. When I made this, I assumed that there could only be a single operation in between two numbers, which clearly isn't true when summing negative numbers. In fact, one can have any number of + and - in between two numbers in any combination. I also realized that calc uses "**" as an alternative way of specifying exponentiation, so I need to allow for that as well.

I modified the main regexp used by math-at-point to allow for these. The modified version is in the "sum-negative" branch (https://github.com/shankar2k/math-at-point/tree/sum-negative). Please try it out and let me know if it works for you.

**Comment by daemianmack** [comment]
Works great so far -- I'll continue to use it and will chime in here if anything unexpected happens. Thanks!
